-- Disable RLS on ALL public tables for single-family app
-- This app has no authentication, so RLS is not needed

-- Core tables
ALTER TABLE IF EXISTS public.accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.categorisation_rules DISABLE ROW LEVEL SECURITY;

-- Budget & Documents
ALTER TABLE IF EXISTS public.budgets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.document_embeddings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;

-- Family Members
ALTER TABLE IF EXISTS public.family_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.member_documents DISABLE ROW LEVEL SECURITY;

-- Schools & Education
ALTER TABLE IF EXISTS public.schools DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.school_years DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.school_terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.school_enrolments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.school_fees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.extracurriculars DISABLE ROW LEVEL SECURITY;

-- Lookup tables
ALTER TABLE IF EXISTS public.fee_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.activity_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.frequencies DISABLE ROW LEVEL SECURITY;

-- Tax & Super
ALTER TABLE IF EXISTS public.tax_returns DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.incomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.deductions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.super_accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.super_contributions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.hecs_debts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tax_estimates DISABLE ROW LEVEL SECURITY;

-- Trust
ALTER TABLE IF EXISTS public.trusts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trust_beneficiaries DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trust_incomes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trust_distributions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trust_investments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.franking_credits DISABLE ROW LEVEL SECURITY;

-- SMSF
ALTER TABLE IF EXISTS public.smsf_funds DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_contributions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_investments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_pensions DISABLE ROW LEVEL SECURITY;

-- Assets & Liabilities
ALTER TABLE IF EXISTS public.assets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.liabilities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.net_worth_snapshots DISABLE ROW LEVEL SECURITY;

-- Xero Integration
ALTER TABLE IF EXISTS public.xero_connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.xero_account_mappings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.xero_sync_logs DISABLE ROW LEVEL SECURITY;

-- Whitelist
ALTER TABLE IF EXISTS public.whitelist DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.whitelisted_users DISABLE ROW LEVEL SECURITY;

-- AI & API
ALTER TABLE IF EXISTS public.ai_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ai_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.api_usage DISABLE ROW LEVEL SECURITY;

-- Bank connections
ALTER TABLE IF EXISTS public.bank_connections DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bank_sync_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.connected_accounts DISABLE ROW LEVEL SECURITY;

-- Additional tables with alternate names
ALTER TABLE IF EXISTS public.hecs_debt DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.income DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trust_income DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_carry_forward DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_compliance DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.smsf_transactions DISABLE ROW LEVEL SECURITY;

-- Users
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;

-- Drop ALL existing RLS policies (generic approach)
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE schemaname = 'public'
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
    END LOOP;
END $$;
